[package]
name = "rustleaks-compat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rustleaks-core = { path = "../rustleaks-core", version = "=0.1.0-alpha.3" }
rustleaks-report = { path = "../rustleaks-report", version = "=0.1.0-alpha.3" }
rustleaks-sources = { path = "../rustleaks-sources", version = "=0.1.0-alpha.3" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
