version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Detroit
    open-pull-requests-limit: 1
    groups:
      rust-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      rust-security-fixes:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: America/Detroit
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:45"
      timezone: America/Detroit
    open-pull-requests-limit: 1
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
