module(
    name = "rustleaks",
    version = "0.1.0-alpha.1",
)

bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "git", version = "2.55.0")
bazel_dep(name = "llvm", version = "0.8.11")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_rust", version = "0.72.0")

single_version_override(
    module_name = "git",
    patch_strip = 1,
    patches = ["//bazel:git_macos_no_fsmonitor.patch"],
    version = "2.55.0",
)

register_toolchains("@llvm//toolchain:all")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    extra_target_triples = [
        "aarch64-apple-darwin",
        "aarch64-pc-windows-msvc",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-linux-musl",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
        "x86_64-unknown-linux-musl",
    ],
    versions = ["1.85.0"],
)
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.render_config(
    platforms_template = "@@//platforms:{triple}",
    regen_command = "just deps-repin",
    repositories = ["crates"],
)
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    isolated = True,
    lockfile = "//:cargo-bazel-lock.json",
    manifests = ["//:Cargo.toml"],
    supported_platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-pc-windows-msvc",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-linux-musl",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
        "x86_64-unknown-linux-musl",
    ],
)
use_repo(crate, "crates")
