[package]
name = "rustleaks-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rustleaks-core = { path = "../rustleaks-core", version = "=0.1.0-alpha.1" }
rustleaks-report = { path = "../rustleaks-report", version = "=0.1.0-alpha.1" }
rustleaks-sources = { path = "../rustleaks-sources", version = "=0.1.0-alpha.1", features = ["archives"] }

[lints]
workspace = true

[[bin]]
name = "rustleaks"
path = "src/main.rs"
