//! Dual-Go/Rust black-box generation and verification of the CLI corpus.

mod fixture;
mod normalize;
mod observe;
mod process;
mod spec;
mod validation;

use std::fs;
use std::path::Path;

use serde_json::Value;

use super::artifacts::GeneratedTree;
use super::support::TempDir;

const README: &str = r"# CLI compatibility corpus v1

Generated by `cargo xtask generate cli` from pinned Go revision
`b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b` and the Rust CLI source hashes in `manifest-v1.json`.

The 34 JSONL rows map one-to-one to `CLI-BB-001..034`; their 119
variants include 119 Go/Rust observation pairs
(238 bounded, isolated observation processes and 242 CLI processes
including build-version and baseline-seed probes). Stable stdout and raw report bytes are retained
as base64. Stderr is reduced only to severity-preserving event classes and
required counts/fields after ANSI, executable, duration, temporary-root,
native-separator, and OS-error normalization. JSON reports additionally
retain complete findings sorted canonically without deduplication.
The configured `-1` finding exit retains its native process status contract:
Unix `255` and Windows signed `-1` normalize to one portable observation.
Timeout and output-bound fixtures use one native helper executable so child
cancellation remains directly observable on every host.

`CLI-SAFE-001..005` are explicit versioned dispositions. Completion omission
and the reviewed safe-template capability boundary are separately versioned;
no unexplained axis difference is accepted. Material mutation controls cover
precedence swaps, redact grammar, surplus-argument source entry, dormant
report flags, stdout inference, terminal exit/report ordering, disclosure,
truncation and report-open failure, help/persistent/shorthand/template
grammar, report bytes, duplicate-preserving findings, exit selection,
stderr severity, and timeout/output-limit child cleanup.

Selected Go version/platform, Rust host, and cleanup strategy are independently
queried and mutation-tested before being omitted from exact outcomes. This
keeps committed artifacts host-independent. The generator has bounded native
process-tree cleanup. `native-linux-v1.json` records the byte-path observation
captured and replayed by native Linux CI; non-Linux generation reuses that
committed observation while native Linux regenerates and compares it exactly.
`unix-path-v1.json` similarly preserves the Unix-only logical Windows-path
fixture for native Windows generation.
`unix-logical-name-v1.json` preserves the Unix filename that contains a
Windows drive spelling and therefore cannot be created by native Windows.
Native Linux and Windows CI also replay the pinned oracle generators before
running the complete native Bazel test suite.

Regenerate with `cargo xtask generate cli`; verify byte-for-byte determinism
with `cargo xtask generate cli --check`. Use `--output PATH` to write elsewhere.
";

pub(crate) use validation::validate_cli_manifest_baselines;

pub(crate) fn check_cli_corpus(root: &Path) -> Result<(), String> {
    let test_manifest = fs::read_to_string(root.join("compat/test-manifest.toml"))
        .map_err(|error| format!("cannot read test manifest: {error}"))?;
    validate_cli_manifest_baselines(root, &test_manifest)?;
    generate_and_apply(root, &root.join("compat/cli-corpus"), true)
}

pub(crate) fn write_cli_corpus(root: &Path, output_root: &Path) -> Result<(), String> {
    generate_and_apply(root, output_root, false)
}

fn generate_and_apply(root: &Path, output_root: &Path, check: bool) -> Result<(), String> {
    let tree = generate(root)?;
    tree.write_or_check(output_root, check)?;
    println!(
        "cli corpus: 34 cases, 119 variants, 242 fresh CLI processes (119 pairs/238 observation processes)"
    );
    Ok(())
}

fn generate(root: &Path) -> Result<GeneratedTree, String> {
    let corpus = root.join("compat/cli-corpus");
    let requests = read(&corpus.join("requests-v1.jsonl"))?;
    let negative = read(&corpus.join("negative-controls-v1.json"))?;
    let native_linux = read(&corpus.join("native-linux-v1.json"))?;
    let unix_path = read(&corpus.join("unix-path-v1.json"))?;
    let unix_logical_name = read(&corpus.join("unix-logical-name-v1.json"))?;
    let legacy_manifest = read(&corpus.join("manifest-v1.json"))?;
    let negative_value = parse_json(&negative, "CLI negative controls")?;
    let manifest_value = parse_json(&legacy_manifest, "CLI manifest")?;
    let native_linux_text = std::str::from_utf8(&native_linux)
        .map_err(|error| format!("native Linux CLI evidence is not UTF-8: {error}"))?;
    let unix_path_text = std::str::from_utf8(&unix_path)
        .map_err(|error| format!("Unix path CLI evidence is not UTF-8: {error}"))?;
    let unix_logical_name_text = std::str::from_utf8(&unix_logical_name)
        .map_err(|error| format!("Unix logical-name CLI evidence is not UTF-8: {error}"))?;
    let rows = spec::validate_inputs(&requests, &negative, &negative_value, &manifest_value)?;
    let upstream = root
        .parent()
        .ok_or_else(|| format!("repository root {} has no parent", root.display()))?
        .join("gitleaks");
    let temporary = TempDir::new("cli-corpus-build")?;
    spec::validate_sources(root, &upstream, &manifest_value)?;
    let runtime = spec::selected_runtime(root, &upstream, &temporary)?;
    let status_before = spec::git_status(&upstream, &temporary, "upstream-before")?;
    let binaries = spec::build(root, &upstream, &temporary, &runtime)?;

    let mut outcomes = Vec::new();
    for row in &rows {
        outcomes.extend_from_slice(
            observe::row_json(
                row,
                &binaries.go,
                &binaries.rust,
                &binaries.fake_git,
                native_linux_text,
                unix_path_text,
                unix_logical_name_text,
            )?
            .as_bytes(),
        );
    }
    validation::validate_outcomes(&outcomes, &manifest_value)?;
    spec::validate_sources(root, &upstream, &manifest_value)?;
    let final_runtime = spec::selected_runtime(root, &upstream, &temporary)?;
    if final_runtime != runtime {
        return Err("runtime provenance changed during CLI generation".into());
    }
    if spec::git_status(&upstream, &temporary, "upstream-after")? != status_before {
        return Err("upstream checkout changed during CLI generation".into());
    }
    let generator_hash = crate::tooling::support::source_tree_sha256(
        root,
        &root.join("crates/xtask/src/tooling/cli_corpus"),
    )?;
    let manifest = validation::render_manifest(
        &legacy_manifest,
        &manifest_value,
        &generator_hash,
        &crate::tooling::support::sha256_bytes(&native_linux),
        &crate::tooling::support::sha256_bytes(&unix_path),
        &crate::tooling::support::sha256_bytes(&unix_logical_name),
    )?;

    let mut tree = GeneratedTree::default();
    tree.insert("requests-v1.jsonl", requests)?;
    tree.insert("outcomes-v1.jsonl", outcomes)?;
    tree.insert("negative-controls-v1.json", negative)?;
    tree.insert("native-linux-v1.json", native_linux)?;
    tree.insert("unix-path-v1.json", unix_path)?;
    tree.insert("unix-logical-name-v1.json", unix_logical_name)?;
    tree.insert("manifest-v1.json", manifest)?;
    tree.insert("README.md", README.as_bytes())?;
    Ok(tree)
}

fn parse_json(bytes: &[u8], label: &str) -> Result<Value, String> {
    serde_json::from_slice(bytes).map_err(|error| format!("invalid {label} JSON: {error}"))
}

fn read(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|error| format!("cannot read {}: {error}", path.display()))
}

fn newline_records<'a>(bytes: &'a [u8], label: &str) -> Result<Vec<&'a [u8]>, String> {
    if !bytes.ends_with(b"\n") {
        return Err(format!("{label} JSONL lacks final newline"));
    }
    let mut records = Vec::new();
    let mut start = 0;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte == b'\n' {
            if index == start {
                return Err(format!("{label} contains blank line"));
            }
            records.push(&bytes[start..=index]);
            start = index + 1;
        }
    }
    Ok(records)
}

#[cfg(test)]
mod tests {
    use super::newline_records;
    #[test]
    fn jsonl_boundaries_fail_closed() {
        assert!(newline_records(b"{}", "test").is_err());
        assert!(newline_records(b"{}\n\n", "test").is_err());
        assert_eq!(newline_records(b"{}\n[]\n", "test").unwrap().len(), 2);
    }
}
