#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate compact simple-lowercase ranges from the pinned Go toolchain's
# Unicode tables. The committed Rust table keeps production builds independent
# of Go while making keyword normalization explicitly Unicode-versioned.

require "open3"
require "pathname"
require "tmpdir"

ROOT = Pathname(__dir__).parent
OUTPUT = ROOT.join("crates/rustleaks-core/src/go_lowercase_tables.rs")
EXPECTED_UNICODE = "15.0.0"
CHECK = ARGV.delete("--check")
abort "usage: #{$PROGRAM_NAME} [--check]" unless ARGV.empty?

source = <<~GO
  package main
  import (
    "fmt"
    "unicode"
    "unicode/utf8"
  )
  func main() {
    fmt.Println(unicode.Version)
    for value := rune(0); value <= utf8.MaxRune; value++ {
      lower := unicode.ToLower(value)
      if lower != value {
        fmt.Printf("%X %X\\n", value, lower)
      }
    }
  }
GO

output = Dir.mktmpdir("rustleaks-go-lowercase") do |directory|
  path = Pathname(directory).join("main.go")
  path.binwrite(source)
  go_environment = { "GOCACHE" => Pathname(directory).join("cache").to_s }
  stdout, stderr, status = Open3.capture3(go_environment, "go", "run", path.to_s)
  abort "Go lowercase generator failed:\n#{stderr}" unless status.success?
  stdout
end

lines = output.lines(chomp: true)
unicode_version = lines.shift
abort "unexpected Go Unicode version #{unicode_version}" unless unicode_version == EXPECTED_UNICODE
pairs = lines.map { |line| line.split.map { |value| Integer(value, 16) } }

ranges = []
pairs.each do |source_value, target_value|
  delta = target_value - source_value
  previous = ranges.last
  if previous
    step = previous[2]
    candidate_step = source_value - previous[1]
    step = candidate_step if previous[0] == previous[1]
    if delta == previous[3] && candidate_step == step
      previous[1] = source_value
      previous[2] = step
      next
    end
  end
  ranges << [source_value, source_value, 1, delta]
end

rendered = <<~RUST
  // @generated by compat/generate_go_lowercase.rb; do not edit manually.
  // Go unicode.Version: #{unicode_version}
  pub(crate) const GO_LOWERCASE_RANGES: &[(u32, u32, u32, i32)] = &[
  #{ranges.map { |low, high, step, delta| format("    (0x%X, 0x%X, %d, %d),", low, high, step, delta) }.join("\n")}
  ];
RUST

if CHECK
  abort "generated Go lowercase table differs" unless OUTPUT.binread == rendered
else
  OUTPUT.binwrite(rendered)
end
