//! Pinned-Go generation and verification of the configuration corpus.

mod filetree;
mod metadata;
mod process;
mod spec;
mod validation;

use std::path::Path;

use super::artifacts::GeneratedTree;
use super::support::TempDir;

const README: &str = r"# Canonical Go configuration corpus

Generated by `cargo xtask generate config` from pinned upstream
`b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b`. Every one of the 112 cases runs in a fresh Go
process and a separate temporary copy of the configuration fixture tree, so
upstream's process-global extension-depth counter cannot leak between cases.

The corpus contains all 50 copied `testdata/config`
TOMLs, the byte-exact pinned default TOML, and 61
focused permissiveness, validation, alias, required-rule, diagnostic, and
extension cases. `outcomes-v1.jsonl` has 75 successful effective
configurations and 37 structured errors/panics.

Canonicalization is deliberately narrow: rule-map keys and the global keyword
set are sorted; commits and stop words are sorted only because upstream
rebuilds those semantic sets from Go maps. Ordered rules, duplicates, tags,
keywords, required rules, patterns, target rules, and allowlist order remain
observable and unchanged.

`TM-0029..TM-0031` and `TM-0034..TM-0072` cover configuration construction.
`TM-0028`, `TM-0032`, and `TM-0033` are covered by the allowlist and GoRegex
execution corpora instead.

Regenerate with:

```sh
cargo xtask generate config
cargo xtask generate config --check
```
";

/// Rebuild the configuration corpus and compare every byte with the committed tree.
pub(crate) fn check_config_corpus(root: &Path) -> Result<(), String> {
    generate_and_apply(root, &root.join("compat/config-corpus"), true)
}

/// Rebuild the configuration corpus into an explicit output directory.
pub(crate) fn write_config_corpus(root: &Path, output_root: &Path) -> Result<(), String> {
    generate_and_apply(root, output_root, false)
}

fn generate_and_apply(root: &Path, output_root: &Path, check: bool) -> Result<(), String> {
    let canonical = spec::load(root)?;
    let upstream = root
        .parent()
        .ok_or_else(|| format!("repository root {} has no parent", root.display()))?
        .join("gitleaks");
    let temporary = TempDir::new("config-corpus")?;
    let observed = process::observe(root, &upstream, &canonical, &temporary)?;
    let summary = validation::validate_all(&canonical, &observed)?;

    let mut tree = GeneratedTree::default();
    tree.insert("README.md", README.as_bytes())?;
    tree.insert("schema-v1.json", canonical.schema)?;
    tree.insert("manifest-v1.json", canonical.manifest)?;
    tree.insert("inputs-v1.jsonl", canonical.inputs)?;
    tree.insert("requests-v1.jsonl", canonical.requests)?;
    tree.insert("outcomes-v1.jsonl", observed.outcomes)?;
    tree.insert("default-gitleaks.toml", observed.default_config)?;
    tree.write_or_check(output_root, check)?;

    println!(
        "config corpus: {} cases ({} effective, {} errors), outcomes {}",
        summary.case_count, summary.success_count, summary.error_count, summary.outcomes_sha256
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::README;

    #[test]
    fn readme_changes_only_command_provenance() {
        assert!(README.contains("Generated by `cargo xtask generate config`"));
        assert!(README.contains("cargo xtask generate config --check"));
        assert!(!README.contains(".rb"));
        assert_eq!(README.matches("112").count(), 1);
        assert_eq!(README.matches("50").count(), 1);
        assert_eq!(README.matches("61").count(), 1);
    }
}
