use std::collections::BTreeSet;
use std::path::Path;

use super::records::{json_string, required, section_records, table};
use crate::tooling::support::sha256_file;

pub(super) fn validate(root: &Path, manifest: &str) -> Result<(), String> {
    validate_header(manifest)?;
    validate_totals(manifest)?;
    validate_corpora(root, manifest)?;
    validate_mappings(manifest)
}

fn validate_header(manifest: &str) -> Result<(), String> {
    if !manifest.starts_with("# Generated by cargo xtask generate inventory;") {
        return Err("test manifest does not identify the Rust inventory generator".into());
    }
    for required in [
        "schema_version = 1",
        "upstream_revision = \"b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b\"",
        "status = \"understanding-complete\"",
    ] {
        if !manifest.contains(required) {
            return Err(format!("test manifest lacks required header {required:?}"));
        }
    }
    Ok(())
}

fn validate_totals(manifest: &str) -> Result<(), String> {
    let totals = table(manifest, "expected_totals")?;
    for required in [
        "packages = 16",
        "exported_api_identities = 607",
        "test_files = 19",
        "active_top_level_tests = 41",
        "nested_test_identities = 234",
        "macos_test_identities = 275",
        "benchmarks = 8",
        "exported_rule_constructors = 225",
        "default_rules = 222",
        "selected_helper_validations = 220",
        "non_t_run_assertion_cases = 283",
        "benchmark_correctness_assertions = 6",
        "platform_skip_branches = 2",
        "deterministic_git_intentions = 7",
        "testdata_files = 214",
        "testdata_symlinks = 1",
    ] {
        if !totals.lines().any(|line| line == required) {
            return Err(format!(
                "test manifest lacks required baseline {required:?}"
            ));
        }
    }
    let fixtures = table(manifest, "fixture_set")?;
    for required in [
        "regular_record_stream_sha256 = \"a29bcb807fc5466fb38bba0134fe6d5f41364e9efeae4980225cc21524fd4ed1\"",
        "regular_git_mode_100644 = 210",
        "regular_git_mode_100755 = 4",
        "symlink_git_mode_120000 = 1",
        "symlink_target = \"../source_file/id_ed25519\"",
        "tracked_entries = 215",
        "ascii_paths = 215",
        "invalid_utf8_regular_payloads = 67",
    ] {
        if !fixtures.lines().any(|line| line == required) {
            return Err(format!(
                "test manifest lacks required fixture baseline {required:?}"
            ));
        }
    }
    Ok(())
}

fn validate_corpora(root: &Path, manifest: &str) -> Result<(), String> {
    let traceability = table(manifest, "traceability_corpora")?;
    let pairs = traceability
        .lines()
        .filter_map(|line| line.split_once(" = "))
        .collect::<std::collections::BTreeMap<_, _>>();
    for (path_key, hash_key) in [
        ("api_inventory", "api_inventory_sha256"),
        ("api_dispositions", "api_dispositions_sha256"),
        ("assertions", "assertions_sha256"),
        ("benchmark_links", "benchmark_links_sha256"),
        ("platform_skips", "platform_skips_sha256"),
        ("generator_constructors", "generator_constructors_sha256"),
        ("generator_samples", "generator_samples_sha256"),
        ("config_requests", "config_requests_sha256"),
        ("config_outcomes", "config_outcomes_sha256"),
        ("regex_expressions", "regex_expressions_sha256"),
        ("regex_requests_path", "regex_requests_sha256"),
        ("regex_request_metadata", "regex_request_metadata_sha256"),
        ("regex_outcomes", "regex_outcomes_sha256"),
    ] {
        let raw_path = pairs
            .get(path_key)
            .ok_or_else(|| format!("traceability_corpora lacks {path_key}"))?;
        let relative: String = serde_json::from_str(raw_path)
            .map_err(|error| format!("invalid {path_key}: {error}"))?;
        let expected: String = serde_json::from_str(
            pairs
                .get(hash_key)
                .ok_or_else(|| format!("traceability_corpora lacks {hash_key}"))?,
        )
        .map_err(|error| format!("invalid {hash_key}: {error}"))?;
        let actual = sha256_file(&root.join(&relative))?;
        if actual != expected {
            return Err(format!(
                "{hash_key} mismatch for {relative}: expected {expected}, got {actual}"
            ));
        }
    }
    Ok(())
}

fn validate_mappings(manifest: &str) -> Result<(), String> {
    for (marker, expected) in [
        ("[[api_package]]", 16),
        ("[[test_file]]", 19),
        ("[[case]]", 275),
        ("[[benchmark]]", 8),
        ("[[git_intention]]", 7),
        ("[[generator_constructor]]", 225),
        ("[[fixture]]", 215),
        ("top_level = true", 41),
        ("top_level = false", 234),
        ("disposition = \"selected-default\"", 222),
        ("disposition = \"excluded-by-upstream-default\"", 3),
        ("helper = \"validate\"", 218),
        ("helper = \"validate_with_paths\"", 5),
        ("helper = \"none\"", 2),
        ("kind = \"regular\"", 214),
        ("kind = \"symlink\"", 1),
        ("platform_skip_reason = ", 2),
    ] {
        let found = manifest.matches(marker).count();
        if found != expected {
            return Err(format!(
                "test manifest marker {marker:?} count mismatch: expected {expected}, got {found}"
            ));
        }
    }
    if manifest.contains("consumers = []") {
        return Err("test manifest contains a fixture without a consumer mapping".into());
    }
    let ids = section_records(manifest, "generator_constructor")
        .into_iter()
        .map(|row| {
            json_string(
                required(&row, "rule_id", "generator_constructor")?,
                "generator_constructor rule_id",
            )
        })
        .collect::<Result<Vec<_>, String>>()?;
    let unique = ids.iter().collect::<BTreeSet<_>>();
    if ids.len() != 225 || ids.iter().any(String::is_empty) || unique.len() != 225 {
        return Err("generator constructor rule_id mappings are missing or duplicated".into());
    }
    Ok(())
}
