//! Pinned-upstream mechanical inventory generation and final traceability checks.

mod baselines;
mod controls;
mod discovery;
mod mechanical;
mod model;
mod process;
mod provenance;
mod records;
mod traceability;

use std::fs;
use std::path::Path;

/// Generates the final inventory bytes after independently rediscovering every
/// mechanical upstream identity and validating all committed traceability links.
pub(crate) fn generate_inventory(root: &Path) -> Result<Vec<u8>, String> {
    let manifest_path = root.join("compat/test-manifest.toml");
    let canonical = read_text(&manifest_path)?;
    let behavior = read_text(&root.join("compat/behavior-matrix.toml"))?;
    let api = read_text(&root.join("compat/api-dispositions-v1.jsonl"))?;
    let inventory = discovery::discover(root)?;
    mechanical::verify(&inventory, &canonical)?;
    traceability::verify(&canonical, &behavior, &api)?;
    let generated = provenance::transition(root, &canonical)?;
    baselines::validate(root, &generated)?;
    controls::run(&inventory, &generated, &generated, &behavior, &api)?;
    Ok(generated.into_bytes())
}

/// Writes the single inventory artifact to an explicit path.
pub(crate) fn write_inventory(root: &Path, output: &Path) -> Result<(), String> {
    let generated = generate_inventory(root)?;
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
    }
    fs::write(output, &generated)
        .map_err(|error| format!("cannot write {}: {error}", output.display()))?;
    println!("wrote 275 cases, 8 benchmarks, 225 constructors, 215 fixtures");
    Ok(())
}

/// Checks an explicit candidate path byte-for-byte after running all discovery,
/// traceability, final-status, and mutation controls.
pub(crate) fn check_inventory(root: &Path, candidate: &Path) -> Result<(), String> {
    let generated = generate_inventory(root)?;
    let actual = fs::read(candidate)
        .map_err(|error| format!("cannot read {}: {error}", candidate.display()))?;
    if actual != generated {
        let offset = actual
            .iter()
            .zip(&generated)
            .position(|(left, right)| left != right)
            .unwrap_or(actual.len().min(generated.len()));
        return Err(format!(
            "inventory candidate {} differs at byte {offset}: expected {} bytes, got {}",
            candidate.display(),
            generated.len(),
            actual.len()
        ));
    }
    println!(
        "verified exact mechanical identities and negative substitution: 275 cases, 8 benchmarks, 225 constructors, 215 fixtures"
    );
    Ok(())
}

fn read_text(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("cannot read {}: {error}", path.display()))
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use super::*;

    static INVENTORY_TEST_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn generated_inventory_is_idempotent() {
        let _guard = INVENTORY_TEST_LOCK.lock().expect("inventory test lock");
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("canonical workspace root");
        let canonical = read_text(&root.join("compat/test-manifest.toml")).expect("read manifest");
        let generated = String::from_utf8(generate_inventory(&root).expect("generate inventory"))
            .expect("inventory is UTF-8");
        let rust_header =
            "# Generated by cargo xtask generate inventory; coordinator annotations may follow.";
        assert!(canonical.starts_with(rust_header));
        assert!(generated.starts_with(rust_header));
        assert_eq!(generated, canonical);
    }

    #[test]
    fn explicit_candidate_mode_supports_spaces_and_non_ascii() {
        let _guard = INVENTORY_TEST_LOCK.lock().expect("inventory test lock");
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("canonical workspace root");
        let temporary = crate::tooling::support::TempDir::new("inventory-candidate")
            .expect("temporary directory");
        let candidate = temporary.path.join("nested space Ω/test-manifest.toml");
        crate::tooling::write_inventory(&root, &candidate).expect("write explicit inventory");
        crate::tooling::check_inventory(&root, &candidate).expect("check explicit inventory");
    }
}
