use std::path::Path;

use crate::tooling::support::{sha256_file, source_tree_sha256};

const RUST_HEADER: &str =
    "# Generated by cargo xtask generate inventory; coordinator annotations may follow.";

pub(super) fn transition(root: &Path, canonical: &str) -> Result<String, String> {
    if !canonical.starts_with(RUST_HEADER) {
        return Err("test manifest has an unknown generator header".into());
    }
    let mut output = canonical.to_owned();
    ensure_cli_native_linux_field(root, &mut output)?;
    ensure_cli_unix_path_field(root, &mut output)?;
    transition_cli_native_metrics(&mut output)?;
    refresh_artifact_hashes(root, &mut output)?;
    let generators = [
        (
            "source",
            "crates/xtask/src/tooling/source",
            "cargo xtask generate source",
        ),
        (
            "git",
            "crates/xtask/src/tooling/git_corpus",
            "cargo xtask generate git",
        ),
        (
            "report",
            "crates/xtask/src/tooling/report",
            "cargo xtask generate report",
        ),
        (
            "cli",
            "crates/xtask/src/tooling/cli_corpus",
            "cargo xtask generate cli",
        ),
    ];
    let mut additions = Vec::new();
    for (name, relative, command) in generators {
        let path = root.join(relative);
        if !path.is_dir() {
            return Err(format!(
                "Rust {name} generator source tree is missing: {}",
                path.display()
            ));
        }
        let digest = source_tree_sha256(root, &path)?;
        replace_string_value(&mut output, &format!("{name}_generator_sha256"), &digest)?;
        additions.push(format!("{name}_generator_source = {}", json(relative)));
        additions.push(format!("{name}_generator_command = {}", json(command)));
    }
    let samples = root.join("crates/xtask/src/tooling/traceability/generator_samples");
    if samples.is_dir() {
        additions.push(format!(
            "generator_samples_generator_sha256 = {}",
            json(&source_tree_sha256(root, &samples)?)
        ));
        additions.push("generator_samples_generator_source = \"crates/xtask/src/tooling/traceability/generator_samples\"".into());
        additions.push(
            "generator_samples_generator_command = \"cargo xtask generate generator-samples\""
                .into(),
        );
    }
    let inventory = root.join("crates/xtask/src/tooling/inventory");
    additions.push(format!(
        "inventory_generator_sha256 = {}",
        json(&source_tree_sha256(root, &inventory)?)
    ));
    additions.push("inventory_generator_source = \"crates/xtask/src/tooling/inventory\"".into());
    additions.push("inventory_generator_command = \"cargo xtask generate inventory\"".into());
    insert_at_end_of_table(&mut output, "traceability_corpora", &additions)?;
    Ok(output)
}

fn ensure_cli_unix_path_field(root: &Path, output: &mut String) -> Result<(), String> {
    if output.contains("cli_unix_path_sha256 = ") {
        return Ok(());
    }
    let marker = "cli_native_linux_sha256 = \"";
    let start = output
        .find(marker)
        .ok_or("test manifest lacks cli_native_linux_sha256")?;
    let end = start
        + output[start..]
            .find('\n')
            .ok_or("test manifest has malformed cli_native_linux_sha256")?
        + 1;
    let hash = sha256_file(&root.join("compat/cli-corpus/unix-path-v1.json"))?;
    output.insert_str(end, &format!("cli_unix_path_sha256 = \"{hash}\"\n"));
    Ok(())
}

fn transition_cli_native_metrics(output: &mut String) -> Result<(), String> {
    for (key, old, new) in [
        ("cli_fresh_processes", "240", "242"),
        ("cli_exact_variants", "100", "101"),
        ("cli_disposition_variants", "19", "18"),
        ("cli_findings_both", "100", "102"),
        ("cli_report_bytes_both", "48732", "49540"),
        ("cli_stderr_events_both", "884", "888"),
    ] {
        let old_line = format!("{key} = {old}\n");
        let new_line = format!("{key} = {new}\n");
        match (
            output.matches(&old_line).count(),
            output.matches(&new_line).count(),
        ) {
            (1, 0) => *output = output.replacen(&old_line, &new_line, 1),
            (0, 1) => {}
            (old_count, new_count) => {
                return Err(format!(
                    "expected one old or current {key}, found {old_count}/{new_count}"
                ));
            }
        }
    }
    Ok(())
}

fn ensure_cli_native_linux_field(root: &Path, output: &mut String) -> Result<(), String> {
    if output.contains("cli_native_linux_sha256 = ") {
        return Ok(());
    }
    let marker = "cli_readme_sha256 = \"";
    let start = output
        .find(marker)
        .ok_or("test manifest lacks cli_readme_sha256")?;
    let end = start
        + output[start..]
            .find('\n')
            .ok_or("test manifest has malformed cli_readme_sha256")?
        + 1;
    let hash = sha256_file(&root.join("compat/cli-corpus/native-linux-v1.json"))?;
    output.insert_str(end, &format!("cli_native_linux_sha256 = \"{hash}\"\n"));
    Ok(())
}

#[allow(clippy::too_many_lines)] // The path-to-field authority is intentionally adjacent and reviewable.
fn refresh_artifact_hashes(root: &Path, output: &mut String) -> Result<(), String> {
    for (key, relative) in [
        ("api_inventory_sha256", "compat/api-inventory-v1.json"),
        (
            "api_dispositions_sha256",
            "compat/api-dispositions-v1.jsonl",
        ),
        (
            "assertions_sha256",
            "compat/assertion-corpus/assertions.jsonl",
        ),
        (
            "benchmark_links_sha256",
            "compat/assertion-corpus/benchmark-links.jsonl",
        ),
        (
            "platform_skips_sha256",
            "compat/assertion-corpus/platform-skips.jsonl",
        ),
        (
            "generator_constructors_sha256",
            "compat/generator-corpus/constructors-v1.jsonl",
        ),
        (
            "generator_samples_sha256",
            "compat/generator-corpus/samples-v1.jsonl",
        ),
        (
            "config_requests_sha256",
            "compat/config-corpus/requests-v1.jsonl",
        ),
        (
            "config_outcomes_sha256",
            "compat/config-corpus/outcomes-v1.jsonl",
        ),
        (
            "regex_expressions_sha256",
            "compat/regex-corpus/expressions-v1.jsonl",
        ),
        (
            "regex_requests_sha256",
            "compat/regex-corpus/requests-v1.jsonl",
        ),
        (
            "regex_request_metadata_sha256",
            "compat/regex-corpus/request-metadata-v1.jsonl",
        ),
        (
            "regex_outcomes_sha256",
            "compat/regex-corpus/outcomes-v1.jsonl",
        ),
        (
            "regex_manifest_sha256",
            "compat/regex-corpus/manifest-v1.json",
        ),
        (
            "detect_requests_sha256",
            "compat/detect-corpus/requests-v1.jsonl",
        ),
        (
            "detect_outcomes_sha256",
            "compat/detect-corpus/outcomes-v1.jsonl",
        ),
        (
            "allowlist_requests_sha256",
            "compat/allowlist-corpus/requests-v1.jsonl",
        ),
        (
            "allowlist_outcomes_sha256",
            "compat/allowlist-corpus/outcomes-v1.jsonl",
        ),
        (
            "allowlist_request_metadata_sha256",
            "compat/allowlist-corpus/request-metadata-v1.jsonl",
        ),
        (
            "allowlist_coverage_sha256",
            "compat/allowlist-corpus/coverage-v1.json",
        ),
        (
            "decoder_requests_sha256",
            "compat/decoder-corpus/requests-v1.jsonl",
        ),
        (
            "decoder_outcomes_sha256",
            "compat/decoder-corpus/outcomes-v1.jsonl",
        ),
        (
            "decoder_request_metadata_sha256",
            "compat/decoder-corpus/request-metadata-v1.jsonl",
        ),
        (
            "decoder_coverage_sha256",
            "compat/decoder-corpus/coverage-v1.json",
        ),
        (
            "composite_requests_sha256",
            "compat/composite-corpus/requests-v1.jsonl",
        ),
        (
            "composite_outcomes_sha256",
            "compat/composite-corpus/outcomes-v1.jsonl",
        ),
        (
            "composite_coverage_sha256",
            "compat/composite-corpus/coverage-v1.json",
        ),
        (
            "composite_negative_controls_sha256",
            "compat/composite-corpus/negative-controls-v1.json",
        ),
        (
            "session_requests_sha256",
            "compat/session-corpus/requests-v1.jsonl",
        ),
        (
            "session_outcomes_sha256",
            "compat/session-corpus/outcomes-v1.jsonl",
        ),
        (
            "session_coverage_sha256",
            "compat/session-corpus/coverage-v1.json",
        ),
        (
            "session_negative_controls_sha256",
            "compat/session-corpus/negative-controls-v1.json",
        ),
        (
            "source_requests_sha256",
            "compat/source-corpus/requests-v1.jsonl",
        ),
        (
            "source_outcomes_sha256",
            "compat/source-corpus/outcomes-v1.jsonl",
        ),
        (
            "source_coverage_sha256",
            "compat/source-corpus/coverage-v1.json",
        ),
        (
            "source_negative_controls_sha256",
            "compat/source-corpus/negative-controls-v1.json",
        ),
        (
            "source_manifest_sha256",
            "compat/source-corpus/manifest-v1.json",
        ),
        ("source_readme_sha256", "compat/source-corpus/README.md"),
        ("git_requests_sha256", "compat/git-corpus/requests-v1.jsonl"),
        ("git_outcomes_sha256", "compat/git-corpus/outcomes-v1.jsonl"),
        ("git_coverage_sha256", "compat/git-corpus/coverage-v1.json"),
        (
            "git_negative_controls_sha256",
            "compat/git-corpus/negative-controls-v1.json",
        ),
        ("git_manifest_sha256", "compat/git-corpus/manifest-v1.json"),
        ("git_readme_sha256", "compat/git-corpus/README.md"),
        (
            "report_requests_sha256",
            "compat/report-corpus/requests-v1.jsonl",
        ),
        (
            "report_outcomes_sha256",
            "compat/report-corpus/outcomes-v1.jsonl",
        ),
        (
            "report_coverage_sha256",
            "compat/report-corpus/coverage-v1.json",
        ),
        ("report_readme_sha256", "compat/report-corpus/README.md"),
        ("cli_requests_sha256", "compat/cli-corpus/requests-v1.jsonl"),
        ("cli_outcomes_sha256", "compat/cli-corpus/outcomes-v1.jsonl"),
        (
            "cli_negative_controls_sha256",
            "compat/cli-corpus/negative-controls-v1.json",
        ),
        ("cli_manifest_sha256", "compat/cli-corpus/manifest-v1.json"),
        ("cli_readme_sha256", "compat/cli-corpus/README.md"),
        (
            "cli_native_linux_sha256",
            "compat/cli-corpus/native-linux-v1.json",
        ),
        (
            "cli_unix_path_sha256",
            "compat/cli-corpus/unix-path-v1.json",
        ),
    ] {
        let path = root.join(relative);
        if !path.is_file() {
            return Err(format!("inventory input is missing: {}", path.display()));
        }
        replace_string_value(output, key, &sha256_file(&path)?)?;
    }
    Ok(())
}

fn replace_string_value(text: &mut String, key: &str, value: &str) -> Result<(), String> {
    let prefix = format!("{key} = \"");
    let start = text
        .find(&prefix)
        .ok_or_else(|| format!("test manifest lacks {key}"))?
        + prefix.len();
    let end = start
        + text[start..]
            .find('"')
            .ok_or_else(|| format!("test manifest has malformed {key}"))?;
    text.replace_range(start..end, value);
    Ok(())
}

fn insert_at_end_of_table(text: &mut String, table: &str, lines: &[String]) -> Result<(), String> {
    let marker = format!("[{table}]\n");
    let start = text
        .find(&marker)
        .ok_or_else(|| format!("manifest lacks [{table}]"))?
        + marker.len();
    let end = start + text[start..].find("\n[").unwrap_or(text.len() - start);
    let mut filtered = text[start..end]
        .lines()
        .filter(|existing| {
            !lines.iter().any(|line| {
                let key = line.split_once(" = ").map_or(line.as_str(), |item| item.0);
                existing.starts_with(&format!("{key} = "))
            })
        })
        .collect::<Vec<_>>()
        .join("\n");
    if !filtered.is_empty() {
        filtered.push('\n');
    }
    filtered.push_str(&lines.join("\n"));
    text.replace_range(start..end, &filtered);
    Ok(())
}

fn json(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}
