//! Pinned-Go generation and verification of the report compatibility corpus.

mod controls;
mod process;
mod spec;
mod validation;

use std::fs;
use std::path::Path;

use serde_json::{Value, json};

use super::artifacts::GeneratedTree;
use super::support::{TempDir, sha256_bytes};
use spec::CASE_COUNT;

const README: &str = r"# Report compatibility corpus v1

Generated by `cargo xtask generate report` from pinned Go revision
`b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b`. Every JSONL request executes in its own bounded oracle process.
Byte-bearing finding, template, and output fields use base64, so invalid UTF-8
and control bytes remain observable.

Runtime Go version and host platform are validated during generation but
omitted from outcomes so the committed corpus is host-independent.

The corpus freezes exact JSON, CSV, JUnit, SARIF, and template bytes; all
pinned upstream report fixtures; report-test identities `TM-0251..TM-0268`;
redaction; ordered SARIF rules; Link/symlink behavior; deterministic safe
template helpers; the three explicitly blocked Sprig helpers; and structured
writer/template/format/request failures. Parse-only cases retain allowed
nondeterministic helpers without executing them.

Regenerate with `cargo xtask generate report`; verify exact determinism with
`cargo xtask generate report --check`.
";

/// Rebuild the report corpus and compare every byte with the committed tree.
pub(crate) fn check_report_corpus(root: &Path) -> Result<(), String> {
    generate_and_apply(root, &root.join("compat/report-corpus"), true)
}

/// Rebuild the report corpus into an explicit output directory.
pub(crate) fn write_report_corpus(root: &Path, output_root: &Path) -> Result<(), String> {
    generate_and_apply(root, output_root, false)
}

fn generate_and_apply(root: &Path, output_root: &Path, check: bool) -> Result<(), String> {
    let generated = generate(root)?;
    generated.tree.write_or_check(output_root, check)?;
    println!(
        "report corpus: {CASE_COUNT} fresh processes, {} output bytes, {} errors",
        generated.output_byte_count, generated.error_case_count
    );
    println!("requests sha256: {}", generated.requests_sha256);
    println!("outcomes sha256: {}", generated.outcomes_sha256);
    Ok(())
}

struct Generated {
    tree: GeneratedTree,
    requests_sha256: String,
    outcomes_sha256: String,
    output_byte_count: u64,
    error_case_count: usize,
}

fn generate(root: &Path) -> Result<Generated, String> {
    let canonical_root = root.join("compat/report-corpus");
    let requests = read(&canonical_root.join("requests-v1.jsonl"))?;
    let committed_outcomes = read(&canonical_root.join("outcomes-v1.jsonl"))?;
    let committed_values = parse_outcomes(&committed_outcomes)?;
    let coverage = read(&canonical_root.join("coverage-v1.json"))?;
    let coverage_value: Value = serde_json::from_slice(&coverage)
        .map_err(|error| format!("invalid report coverage JSON: {error}"))?;
    let request_values = spec::validate_inputs(&requests, &coverage_value)?;

    let upstream = root
        .parent()
        .ok_or_else(|| format!("repository root {} has no parent", root.display()))?
        .join("gitleaks");
    let temporary = TempDir::new("report-corpus")?;
    spec::validate_upstream(&upstream, &coverage_value, &temporary)?;
    let status_before = process::git_status(&upstream, &temporary, "before")?;
    let observed = process::observe(root, &upstream, &request_values, &requests, &temporary)?;
    write_observation_ledger(&observed, &committed_outcomes, &committed_values)?;
    validation::validate_all(
        &upstream,
        &request_values,
        &observed.values,
        &observed.bytes,
        &coverage_value,
    )?;
    if process::git_status(&upstream, &temporary, "after")? != status_before {
        return Err("upstream checkout changed during report generation".into());
    }

    let output_byte_count = observed
        .values
        .iter()
        .map(|outcome| validation::required_u64(outcome, "output_bytes", "outcome"))
        .sum::<Result<u64, _>>()?;
    let error_case_count = observed
        .values
        .iter()
        .filter(|outcome| outcome.get("error").is_some_and(|error| !error.is_null()))
        .count();
    let requests_sha256 = sha256_bytes(&requests);
    let outcomes_sha256 = sha256_bytes(&observed.bytes);
    let mut tree = GeneratedTree::default();
    tree.insert("requests-v1.jsonl", requests)?;
    tree.insert("outcomes-v1.jsonl", observed.bytes)?;
    tree.insert("coverage-v1.json", coverage)?;
    tree.insert("README.md", README.as_bytes())?;
    Ok(Generated {
        tree,
        requests_sha256,
        outcomes_sha256,
        output_byte_count,
        error_case_count,
    })
}

fn parse_outcomes(bytes: &[u8]) -> Result<Vec<Value>, String> {
    newline_records(bytes, "committed report outcomes")?
        .into_iter()
        .enumerate()
        .map(|(index, line)| {
            serde_json::from_slice(line).map_err(|error| {
                format!(
                    "committed report outcome {} is invalid JSON: {error}",
                    index + 1
                )
            })
        })
        .collect()
}

fn observation_ledger(
    observed: &process::Observed,
    committed_bytes: &[u8],
    committed_values: &[Value],
) -> Result<Vec<u8>, String> {
    let observed_lines = newline_records(&observed.bytes, "observed report outcomes")?;
    let committed_lines = newline_records(committed_bytes, "committed report outcomes")?;
    if observed_lines.len() != observed.values.len()
        || committed_lines.len() != committed_values.len()
        || observed.values.len() != committed_values.len()
    {
        return Err("report observation ledger count changed".into());
    }
    let mut records = Vec::with_capacity(observed.values.len());
    for (((observed_line, observed_value), committed_line), committed_value) in observed_lines
        .iter()
        .zip(&observed.values)
        .zip(&committed_lines)
        .zip(committed_values)
    {
        let id = validation::required_str(observed_value, "id", "report outcome")?;
        if validation::required_str(committed_value, "id", "committed report outcome")? != id {
            return Err("report observation ledger order changed".into());
        }
        let count = |value: &Value, field: &str| -> Result<usize, String> {
            value
                .get(field)
                .and_then(Value::as_array)
                .map(Vec::len)
                .ok_or_else(|| format!("report outcome {id} has no {field} array"))
        };
        records.push(json!({
            "id": id,
            "committed_sha256": sha256_bytes(committed_line),
            "outcome_sha256": sha256_bytes(observed_line),
            "difference_path": crate::tooling::artifacts::first_json_difference(
                committed_value,
                observed_value,
                "",
            ),
            "committed_output_sha256": validation::required_str(
                committed_value,
                "output_sha256",
                id,
            )?,
            "output_sha256": validation::required_str(observed_value, "output_sha256", id)?,
            "committed_output_bytes": validation::required_u64(
                committed_value,
                "output_bytes",
                id,
            )?,
            "output_bytes": validation::required_u64(observed_value, "output_bytes", id)?,
            "committed_redacted_finding_count": count(committed_value, "redacted_findings")?,
            "redacted_finding_count": count(observed_value, "redacted_findings")?,
            "committed_has_error": !committed_value.get("error").is_some_and(Value::is_null),
            "has_error": !observed_value.get("error").is_some_and(Value::is_null),
        }));
    }
    let ledger = json!({
        "schema_version": 1,
        "protocol_version": spec::PROTOCOL_VERSION,
        "oracle_mode": "report",
        "upstream_revision": spec::REVISION,
        "default_config_sha256": spec::DEFAULT_CONFIG_SHA256,
        "go_version": observed.go_version,
        "platform": observed.platform,
        "record_count": records.len(),
        "committed_outcomes_sha256": sha256_bytes(committed_bytes),
        "outcomes_sha256": sha256_bytes(&observed.bytes),
        "records": records,
    });
    let mut bytes = serde_json::to_vec_pretty(&ledger)
        .map_err(|error| format!("cannot render report observation ledger: {error}"))?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn write_observation_ledger(
    observed: &process::Observed,
    committed_bytes: &[u8],
    committed_values: &[Value],
) -> Result<(), String> {
    if let Some(path) = std::env::var_os("RUSTLEAKS_REPORT_LEDGER_PATH") {
        fs::write(
            &path,
            observation_ledger(observed, committed_bytes, committed_values)?,
        )
        .map_err(|error| format!("cannot write report observation ledger: {error}"))?;
    }
    Ok(())
}

fn read(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|error| format!("cannot read {}: {error}", path.display()))
}

fn newline_records<'a>(bytes: &'a [u8], label: &str) -> Result<Vec<&'a [u8]>, String> {
    if !bytes.ends_with(b"\n") {
        return Err(format!("{label} JSONL lacks a final newline"));
    }
    let mut records = Vec::new();
    let mut start = 0;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte == b'\n' {
            if index == start {
                return Err(format!("{label} JSONL contains a blank line"));
            }
            records.push(&bytes[start..=index]);
            start = index + 1;
        }
    }
    Ok(records)
}

#[cfg(test)]
mod tests {
    use serde_json::Value;

    use super::newline_records;
    use super::observation_ledger;
    use super::process::Observed;
    use crate::tooling::support::sha256_bytes;

    #[test]
    fn malformed_jsonl_fails_closed() {
        assert!(newline_records(b"{}", "test").is_err());
        assert!(newline_records(b"{}\n\n", "test").is_err());
        assert_eq!(newline_records(b"{}\n[]\n", "test").unwrap().len(), 2);
    }

    #[test]
    fn observation_ledger_retains_hashes_without_payloads() {
        let committed = br#"{"id":"case","output_sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","output_bytes":1,"redacted_findings":[],"error":null,"payload":"reviewed-fixture-value"}
"#;
        let observed_bytes = br#"{"id":"case","output_sha256":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","output_bytes":2,"redacted_findings":[],"error":null,"payload":"changed-reviewed-fixture-value"}
"#
        .to_vec();
        let observed = Observed {
            values: vec![
                serde_json::from_slice(&observed_bytes[..observed_bytes.len() - 1]).unwrap(),
            ],
            bytes: observed_bytes.clone(),
            go_version: "go1.26.7".into(),
            platform: "windows/arm64".into(),
        };
        let committed_values =
            vec![serde_json::from_slice::<Value>(&committed[..committed.len() - 1]).unwrap()];
        let rendered = observation_ledger(&observed, committed, &committed_values).unwrap();
        assert!(
            !rendered
                .windows(b"reviewed-fixture-value".len())
                .any(|window| window == b"reviewed-fixture-value")
        );
        let ledger: Value = serde_json::from_slice(&rendered).unwrap();
        assert_eq!(ledger["platform"], "windows/arm64");
        assert_eq!(ledger["outcomes_sha256"], sha256_bytes(&observed_bytes));
        assert_eq!(ledger["records"][0]["id"], "case");
        assert_eq!(ledger["records"][0]["difference_path"], "/output_bytes");
    }
}
