//! Pinned-Go generation and verification of the report compatibility corpus.

mod controls;
mod process;
mod spec;
mod validation;

use std::fs;
use std::path::Path;

use serde_json::Value;

use super::artifacts::GeneratedTree;
use super::support::{TempDir, sha256_bytes};
use spec::CASE_COUNT;

const README: &str = r"# Report compatibility corpus v1

Generated by `cargo xtask generate report` from pinned Go revision
`b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b`. Every JSONL request executes in its own bounded oracle process.
Byte-bearing finding, template, and output fields use base64, so invalid UTF-8
and control bytes remain observable.

Runtime Go version and host platform are validated during generation but
omitted from outcomes so the committed corpus is host-independent.

The corpus freezes exact JSON, CSV, JUnit, SARIF, and template bytes; all
pinned upstream report fixtures; report-test identities `TM-0251..TM-0268`;
redaction; ordered SARIF rules; Link/symlink behavior; deterministic safe
template helpers; the three explicitly blocked Sprig helpers; and structured
writer/template/format/request failures. Parse-only cases retain allowed
nondeterministic helpers without executing them.

Regenerate with `cargo xtask generate report`; verify exact determinism with
`cargo xtask generate report --check`.
";

/// Rebuild the report corpus and compare every byte with the committed tree.
pub(crate) fn check_report_corpus(root: &Path) -> Result<(), String> {
    generate_and_apply(root, &root.join("compat/report-corpus"), true)
}

/// Rebuild the report corpus into an explicit output directory.
pub(crate) fn write_report_corpus(root: &Path, output_root: &Path) -> Result<(), String> {
    generate_and_apply(root, output_root, false)
}

fn generate_and_apply(root: &Path, output_root: &Path, check: bool) -> Result<(), String> {
    let generated = generate(root)?;
    generated.tree.write_or_check(output_root, check)?;
    println!(
        "report corpus: {CASE_COUNT} fresh processes, {} output bytes, {} errors",
        generated.output_byte_count, generated.error_case_count
    );
    println!("requests sha256: {}", generated.requests_sha256);
    println!("outcomes sha256: {}", generated.outcomes_sha256);
    Ok(())
}

struct Generated {
    tree: GeneratedTree,
    requests_sha256: String,
    outcomes_sha256: String,
    output_byte_count: u64,
    error_case_count: usize,
}

fn generate(root: &Path) -> Result<Generated, String> {
    let canonical_root = root.join("compat/report-corpus");
    let requests = read(&canonical_root.join("requests-v1.jsonl"))?;
    let coverage = read(&canonical_root.join("coverage-v1.json"))?;
    let coverage_value: Value = serde_json::from_slice(&coverage)
        .map_err(|error| format!("invalid report coverage JSON: {error}"))?;
    let request_values = spec::validate_inputs(&requests, &coverage_value)?;

    let upstream = root
        .parent()
        .ok_or_else(|| format!("repository root {} has no parent", root.display()))?
        .join("gitleaks");
    let temporary = TempDir::new("report-corpus")?;
    spec::validate_upstream(&upstream, &coverage_value, &temporary)?;
    let status_before = process::git_status(&upstream, &temporary, "before")?;
    let observed = process::observe(root, &upstream, &request_values, &requests, &temporary)?;
    validation::validate_all(
        &upstream,
        &request_values,
        &observed.values,
        &observed.bytes,
        &coverage_value,
    )?;
    if process::git_status(&upstream, &temporary, "after")? != status_before {
        return Err("upstream checkout changed during report generation".into());
    }

    let output_byte_count = observed
        .values
        .iter()
        .map(|outcome| validation::required_u64(outcome, "output_bytes", "outcome"))
        .sum::<Result<u64, _>>()?;
    let error_case_count = observed
        .values
        .iter()
        .filter(|outcome| outcome.get("error").is_some_and(|error| !error.is_null()))
        .count();
    let requests_sha256 = sha256_bytes(&requests);
    let outcomes_sha256 = sha256_bytes(&observed.bytes);
    let mut tree = GeneratedTree::default();
    tree.insert("requests-v1.jsonl", requests)?;
    tree.insert("outcomes-v1.jsonl", observed.bytes)?;
    tree.insert("coverage-v1.json", coverage)?;
    tree.insert("README.md", README.as_bytes())?;
    Ok(Generated {
        tree,
        requests_sha256,
        outcomes_sha256,
        output_byte_count,
        error_case_count,
    })
}

fn read(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|error| format!("cannot read {}: {error}", path.display()))
}

fn newline_records<'a>(bytes: &'a [u8], label: &str) -> Result<Vec<&'a [u8]>, String> {
    if !bytes.ends_with(b"\n") {
        return Err(format!("{label} JSONL lacks a final newline"));
    }
    let mut records = Vec::new();
    let mut start = 0;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte == b'\n' {
            if index == start {
                return Err(format!("{label} JSONL contains a blank line"));
            }
            records.push(&bytes[start..=index]);
            start = index + 1;
        }
    }
    Ok(records)
}

#[cfg(test)]
mod tests {
    use super::newline_records;

    #[test]
    fn malformed_jsonl_fails_closed() {
        assert!(newline_records(b"{}", "test").is_err());
        assert!(newline_records(b"{}\n\n", "test").is_err());
        assert_eq!(newline_records(b"{}\n[]\n", "test").unwrap().len(), 2);
    }
}
