//! Pinned-Go generation and verification of the Git compatibility corpus.

mod controls;
mod fixture;
mod process;
mod spec;
mod validation;

use std::fs;
use std::path::Path;

use serde_json::Value;

use super::artifacts::{GeneratedTree, OutcomeBaseline};
use super::support::TempDir;

const README: &str = r"# Git compatibility corpus v1

Generated by `cargo xtask generate git` from pinned Go revision
`b58d3f102cf3a2c84cb7f923d05c25c9b1aed84b`. Each JSONL request is executed in a fresh bounded oracle
process. The oracle recursively copies only the committed `small`, `staged`,
or `archives` fixture into a private temporary directory and renames only
that copy's `dotGit`; committed fixtures and `../gitleaks` stay read-only.

`requests-v1.jsonl` is declarative input. `outcomes-v1.jsonl` records exact
argv tokens, normalized command text, ordered fragments, canonical fragment
and finding multisets, commit metadata, remotes, and structured issues.
Byte-bearing fields are base64. Behavior IDs use the stable `GIT-001..023`
mapping recorded in `coverage-v1.json`.

Regenerate with `cargo xtask generate git`; verify with
`cargo xtask generate git --check`. Use `--output PATH` to write elsewhere.
";

pub(crate) fn check_git_corpus(root: &Path) -> Result<(), String> {
    generate_and_apply(root, &root.join("compat/git-corpus"), true)
}

pub(crate) fn write_git_corpus(root: &Path, output_root: &Path) -> Result<(), String> {
    generate_and_apply(root, output_root, false)
}

fn generate_and_apply(root: &Path, output_root: &Path, check: bool) -> Result<(), String> {
    let generated = generate(root, check)?;
    generated.write_or_check(output_root, check)?;
    println!(
        "Git corpus {}: 34 fresh-process cases, 7 intentions, 19 stable behaviors",
        if check { "verified" } else { "generated" }
    );
    Ok(())
}

fn generate(root: &Path, check: bool) -> Result<GeneratedTree, String> {
    let corpus = root.join("compat/git-corpus");
    let requests = read(&corpus.join("requests-v1.jsonl"))?;
    let coverage = read(&corpus.join("coverage-v1.json"))?;
    let negative = read(&corpus.join("negative-controls-v1.json"))?;
    let legacy_readme = read(&corpus.join("README.md"))?;
    let legacy_manifest = read(&corpus.join("manifest-v1.json"))?;
    let legacy_outcomes = read(&corpus.join("outcomes-v1.jsonl"))?;
    let coverage_value = parse_json(&coverage, "Git coverage")?;
    let negative_value = parse_json(&negative, "Git negative controls")?;
    let manifest_value = parse_json(&legacy_manifest, "Git manifest")?;
    let legacy_outcome_values = parse_jsonl(&legacy_outcomes, "committed Git outcomes")?;
    let request_values = spec::validate_inputs(
        &requests,
        &coverage,
        &coverage_value,
        &negative,
        &negative_value,
        &legacy_readme,
        &manifest_value,
    )?;

    let upstream = root
        .parent()
        .ok_or_else(|| format!("repository root {} has no parent", root.display()))?
        .join("gitleaks");
    let temporary = TempDir::new("git-corpus")?;
    spec::validate_upstream(root, &upstream, &coverage_value, &temporary)?;
    let fixture_root = root.join("compat/fixtures/upstream/testdata/repos");
    let fixture_before = fixture::tree_fingerprint(&fixture_root)?;
    let upstream_before = process::git_status(&upstream, None, &temporary, "upstream-before")?;
    let repository_before = process::git_status(
        root,
        Some("compat/fixtures/upstream/testdata/repos"),
        &temporary,
        "fixture-before",
    )?;
    let observed = process::observe(
        root,
        &upstream,
        &request_values,
        &requests,
        &manifest_value,
        &temporary,
    )?;
    validation::validate_all(
        root,
        &request_values,
        &observed.values,
        OutcomeBaseline {
            values: &legacy_outcome_values,
            bytes: &legacy_outcomes,
        },
        &coverage_value,
        &negative_value,
        &manifest_value,
    )?;
    if fixture::tree_fingerprint(&fixture_root)? != fixture_before
        || process::git_status(
            root,
            Some("compat/fixtures/upstream/testdata/repos"),
            &temporary,
            "fixture-after",
        )? != repository_before
        || process::git_status(&upstream, None, &temporary, "upstream-after")? != upstream_before
    {
        return Err("Git fixture or upstream checkout changed during generation".into());
    }

    let outcome_bytes = if check {
        &legacy_outcomes[..]
    } else {
        &observed.bytes[..]
    };
    let manifest = validation::render_manifest(
        &legacy_manifest,
        &manifest_value,
        legacy_readme.len(),
        README.as_bytes(),
        outcome_bytes,
    )?;
    let mut tree = GeneratedTree::default();
    tree.insert("README.md", README.as_bytes())?;
    tree.insert("requests-v1.jsonl", requests)?;
    tree.insert("outcomes-v1.jsonl", outcome_bytes)?;
    tree.insert("coverage-v1.json", coverage)?;
    tree.insert("negative-controls-v1.json", negative)?;
    tree.insert("manifest-v1.json", manifest)?;
    Ok(tree)
}

fn parse_json(bytes: &[u8], label: &str) -> Result<Value, String> {
    serde_json::from_slice(bytes).map_err(|error| format!("invalid {label} JSON: {error}"))
}

fn parse_jsonl(bytes: &[u8], label: &str) -> Result<Vec<Value>, String> {
    newline_records(bytes, label)?
        .iter()
        .enumerate()
        .map(|(index, line)| {
            serde_json::from_slice(line)
                .map_err(|error| format!("invalid {label} record {}: {error}", index + 1))
        })
        .collect()
}

fn read(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|error| format!("cannot read {}: {error}", path.display()))
}

fn newline_records<'a>(bytes: &'a [u8], label: &str) -> Result<Vec<&'a [u8]>, String> {
    if !bytes.ends_with(b"\n") {
        return Err(format!("{label} JSONL lacks a final newline"));
    }
    let mut records = Vec::new();
    let mut start = 0;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte == b'\n' {
            if index == start {
                return Err(format!("{label} JSONL contains a blank line"));
            }
            records.push(&bytes[start..=index]);
            start = index + 1;
        }
    }
    Ok(records)
}

#[cfg(test)]
mod tests {
    use super::newline_records;

    #[test]
    fn jsonl_boundaries_fail_closed() {
        assert!(newline_records(b"{}", "test").is_err());
        assert!(newline_records(b"{}\n\n", "test").is_err());
        assert_eq!(newline_records(b"{}\n[]\n", "test").unwrap().len(), 2);
    }
}
