load("//bazel:rust_crate.bzl", "rustleaks_build_contract_files", "rustleaks_library")

exports_files(["Cargo.toml"])
rustleaks_build_contract_files()

rustleaks_library(
    name = "compcol",
    compile_data = glob(["src/**/*.bin"]),
    crate_name = "compcol",
    edition = "2024",
    version = "0.3.0-rustleaks.1",
)

[
    rustleaks_library(
        name = "profile_" + profile,
        compile_data = glob(["src/**/*.bin"]),
        crate_features = features,
        crate_name = "compcol",
        docs = False,
        edition = "2024",
        unit_test = profile == "rar2",
        version = "0.3.0-rustleaks.1",
        visibility = ["//visibility:public"],
    )
    for profile, features in {
        "default": [],
        "alloc": ["alloc"],
        "rar2": ["alloc", "rar2"],
        "rar3": ["alloc", "rar3"],
        "rar5": ["alloc", "rar5"],
    }.items()
]

filegroup(
    name = "feature_profiles",
    srcs = [
        ":profile_alloc",
        ":profile_default",
        ":profile_rar2",
        ":profile_rar3",
        ":profile_rar5",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "all_tests",
    tests = [
        ":compcol_doc_test",
        ":compcol_unit_test",
        ":profile_rar2_unit_test",
    ],
    visibility = ["//visibility:public"],
)
