//! Generation of Go-compatible simple-lowercase Unicode ranges.

use std::fmt::Write as _;
use std::fs::{self, File};
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::Duration;

use crate::command_status_with_timeout;

use super::support::TempDir;

const GO_UNICODE_VERSION: &str = "15.0.0";

pub(crate) fn generate_go_lowercase(root: &Path, check: bool) -> Result<(), String> {
    const SOURCE: &str = r#"package main
import (
  "fmt"
  "unicode"
  "unicode/utf8"
)
func main() {
  fmt.Println(unicode.Version)
  for value := rune(0); value <= utf8.MaxRune; value++ {
    lower := unicode.ToLower(value)
    if lower != value {
      fmt.Printf("%X %X\n", value, lower)
    }
  }
}
"#;

    let temporary = TempDir::new("go-lowercase")?;
    let source_path = temporary.path.join("main.go");
    let stdout_path = temporary.path.join("stdout");
    let stderr_path = temporary.path.join("stderr");
    fs::write(&source_path, SOURCE)
        .map_err(|error| format!("cannot write {}: {error}", source_path.display()))?;
    let stdout = File::create(&stdout_path)
        .map_err(|error| format!("cannot create {}: {error}", stdout_path.display()))?;
    let stderr = File::create(&stderr_path)
        .map_err(|error| format!("cannot create {}: {error}", stderr_path.display()))?;
    let mut command = Command::new("go");
    command
        .args(["run"])
        .arg(&source_path)
        .env("GOCACHE", temporary.path.join("cache"))
        .stdout(Stdio::from(stdout))
        .stderr(Stdio::from(stderr));
    if let Err(error) = command_status_with_timeout(
        &mut command,
        Duration::from_secs(120),
        "Go lowercase generator",
    ) {
        let diagnostic = fs::read_to_string(&stderr_path).unwrap_or_default();
        return Err(format!("{error}\n{}", diagnostic.trim()));
    }
    let output = fs::read_to_string(&stdout_path)
        .map_err(|error| format!("cannot read {}: {error}", stdout_path.display()))?;
    let rendered = render(&output)?;
    let destination = root.join("crates/rustleaks-core/src/go_lowercase_tables.rs");
    if check {
        let committed = fs::read(&destination)
            .map_err(|error| format!("cannot read {}: {error}", destination.display()))?;
        if committed != rendered.as_bytes() {
            return Err("generated Go lowercase table differs".into());
        }
    } else {
        fs::write(&destination, rendered)
            .map_err(|error| format!("cannot write {}: {error}", destination.display()))?;
    }
    Ok(())
}

fn render(output: &str) -> Result<String, String> {
    let mut lines = output.lines();
    let unicode_version = lines
        .next()
        .ok_or("Go lowercase generator returned no Unicode version")?;
    if unicode_version != GO_UNICODE_VERSION {
        return Err(format!("unexpected Go Unicode version {unicode_version}"));
    }
    let mut ranges: Vec<(u32, u32, u32, i32)> = Vec::new();
    for (index, line) in lines.enumerate() {
        let mut fields = line.split_whitespace();
        let source = fields
            .next()
            .ok_or_else(|| format!("lowercase line {} has no source", index + 2))?;
        let target = fields
            .next()
            .ok_or_else(|| format!("lowercase line {} has no target", index + 2))?;
        if fields.next().is_some() {
            return Err(format!("lowercase line {} has extra fields", index + 2));
        }
        let source = u32::from_str_radix(source, 16)
            .map_err(|error| format!("invalid lowercase source on line {}: {error}", index + 2))?;
        let target = u32::from_str_radix(target, 16)
            .map_err(|error| format!("invalid lowercase target on line {}: {error}", index + 2))?;
        let delta = i64::from(target) - i64::from(source);
        let delta = i32::try_from(delta)
            .map_err(|_| format!("lowercase delta is out of range on line {}", index + 2))?;
        if let Some(previous) = ranges.last_mut() {
            let mut step = previous.2;
            let candidate_step = source
                .checked_sub(previous.1)
                .ok_or_else(|| "Go lowercase output is not ordered".to_owned())?;
            if previous.0 == previous.1 {
                step = candidate_step;
            }
            if delta == previous.3 && candidate_step == step {
                previous.1 = source;
                previous.2 = step;
                continue;
            }
        }
        ranges.push((source, source, 1, delta));
    }

    let mut rendered = format!(
        "// @generated by `cargo xtask generate go-lowercase`; do not edit manually.\n\
         // Go unicode.Version: {unicode_version}\n\
         pub(crate) const GO_LOWERCASE_RANGES: &[(u32, u32, u32, i32)] = &[\n"
    );
    for (low, high, step, delta) in ranges {
        writeln!(
            &mut rendered,
            "    (0x{low:X}, 0x{high:X}, {step}, {delta}),"
        )
        .expect("writing to String cannot fail");
    }
    rendered.push_str("];\n");
    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use super::render;

    #[test]
    fn ranges_match_the_legacy_compaction_and_rendering() {
        let output = "15.0.0\n41 61\n42 62\n43 63\n100 101\n102 103\n";
        assert_eq!(
            render(output).unwrap(),
            concat!(
                "// @generated by `cargo xtask generate go-lowercase`; do not edit manually.\n",
                "// Go unicode.Version: 15.0.0\n",
                "pub(crate) const GO_LOWERCASE_RANGES: &[(u32, u32, u32, i32)] = &[\n",
                "    (0x41, 0x43, 1, 32),\n",
                "    (0x100, 0x102, 2, 1),\n",
                "];\n",
            )
        );
        assert!(render("15.1.0\n41 61\n").is_err());
        assert!(render("15.0.0\nnot-hex 61\n").is_err());
    }
}
